# Generated by Django 5.1.3 on 2024-11-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento')], max_length=15)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'db_table': 'imovel',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'prédio',
                'verbose_name_plural': 'prédios',
                'db_table': 'predio',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.imovel')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'imagem',
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='predio',
            field=models.ForeignKey(blank=True, db_column='predio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.predio'),
        ),
    ]
