# Generated by Django 5.1.3 on 2024-12-10 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'prédio',
                'verbose_name_plural': 'prédios',
                'db_table': 'predio',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento')], max_length=15)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('ALUGADO', 'Alugado')], default='DISPONIVEL', max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
                ('usuario', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('predio', models.ForeignKey(blank=True, db_column='predio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.predio')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'db_table': 'imovel',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.imovel')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'imagem',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_relacionada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário e Empresa',
                'verbose_name_plural': 'Usuários e Empresas',
                'db_table': 'usuario_empresa',
            },
        ),
    ]
