# Generated by Django 5.1.5 on 2025-01-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarioempresa_user'),
        ('api', '0002_imovel_status_imovel_usuario'),
    ]

    operations = [
    ]
